- west.yml
The current west setup imports every available module, an initial checkout takes forever. Set clone-depth: 1 so that modules get a shallow fetch by default (they can easily be unshallowed if needed) and add a list of modules instead of importing them all, initially just the NXP and STM32 one since those are the ones I know have USB+CAN, segger for RTT just in case.
> west.yml: set clone-depth and add an import allowlist

- .github/workflows/build.yml
Since CANnectivity is currently tracking the Zephyr main branch change the build workflow to run once a day to catch any introduced incompatibilities.
> github: workflows: run build workflow once a day

- README.md
Add instructions for pulling in CANnectivity as a Zephyr module.
> README: add instructions for pulling in CANnectivity as a Zephyr module

- README.md
Use relative links when linking to files within the repository.
> README: use relative links

- app/Kconfig
- app/src/main.c
Add an optional boot banner showing the version of the CANnectivity firmware.
> app: add optional firmware version boot banner

- app/src/cannectivity.h
Document the internal API of the CANnectivity firmware.
> app: document the internal API

- .github/ISSUE_TEMPLATE/001_bug_report.md
Add template for reporting CANnectivity bugs.
> github: add bug report template

- app/src/led.c
Use correct log name in the led.c file. This file handles more than identify callbacks.
> app: led: use correct log name

- app/sample.yaml
- subsys/usb/device/class/Kconfig.gs_usb
- subsys/usb/device/class/gs_usb.c
- subsys/usb/device_next/class/Kconfig.gs_usb
- subsys/usb/device_next/class/gs_usb.c
Make the capturing of hardware timestamps on USB Start of Frame (SoF) events optional and disable it by default.
Capturing the hardware timestamp on SoF improves the accuracy of the time synchronization between the USB host and the device (in the range of ~110 to 20 microseconds depending on the board according to my measurements), but comes with a cost of much higher CPU load.
This does not affect the relative timestamping of CAN RX/TX frames, only their absolute timestamp as compared to the USB host time.
> usb: device: gs_usb: make capturing hardware timestamp on sof optional

- subsys/usb/device/class/gs_usb.c
- subsys/usb/device_next/class/gs_usb.c
Update the path to the network buffer header file, which was recently renamed in Zephyr main branch. Details in https://github.com/zephyrproject-rtos/zephyr/pull/78009
> usb: device: class: gs_usb: update path to network buffer header file

- .github/workflows/build.yml
- app/sample.yaml
- app/src/main.c
Add console harness to the firmware application and run a simple boot test of the firmware application on native_sim in CI.
> app: add console harness and run simple firmware boot test in CI

- .github/dependabot.yml
Configure dependabot to check for updates to Python packages.
> github: dependabot: check for updates to python packages

- app/src/usb.c
Add missing "static" keyword to the cannectivity_usb_vendorcode_handler() function declaration.
> app: usb: declare USB vendor code handler function static

- CMakeLists.txt
- README.md
- app/CMakeLists.txt
- app/Kconfig
- app/Kconfig.sysbuild
- app/sample.yaml
- app/src/cannectivity.h
- app/src/dfu.c
- app/src/main.c
- app/sysbuild-dfu.conf
- app/sysbuild.cmake
- app/sysbuild/mcuboot/app.overlay
- app/sysbuild/mcuboot/boards/frdm_k64f_mk64f12.conf
- app/sysbuild/mcuboot/prj.conf
- boards/extensions/frdm_k64f/frdm_k64f.overlay
- cmake/cannectivity.cmake
- west.yml
- zephyr/module.yml
- app: add support for generating an USB DFU image
- app: add support for USB DFU mode via MCUboot
- app: turn off DFU LED once booted
- boards: add frdm_k64f board extension for testing DFU LED support
- app: add support for triggering DFU mode via DFU button
- README: document DFU mode
> app: add USB Device Firmware Upgrade (DFU) support

- .gitignore
Current /build* ignore pattern will exclude build only in the root of the project.
In some cases it is needed build folder to be located in app folder or anywhere else in the project.
This PR fixes this behaviour.
How to reporduce: Make west put build artefacts into <project root>/app/build folder or just move your folder there. You shall see git showing you about 500 untracked files.
UPDATE: This change allows efectivelly delete the whole build folder with `git clean -xdf`. Please still be carefull using this command anyway.
> Make build excluded over all folders in the project

- 99-cannectivity.rules
- app/Kconfig.sysbuild
Use USB VID:PID 1209:ca02 generously granted by pid.codes by for USB DFU mode by default (see https://pid.codes/1209/CA02/).
> app: use newly granted USB VID:PID 1209:ca02 for DFU by default

- app/src/cannectivity.h
- app/src/led.c
- app/src/main.c
- include/cannectivity/usb/class/gs_usb.h
- subsys/usb/device/class/gs_usb.c
- subsys/usb/device_next/class/gs_usb.c
- tests/subsys/usb/gs_usb/host/src/main.c
- tests/subsys/usb/gs_usb/host/testcase.yaml
Unify the application event callbacks to reduce code complexity and simplify future event additions.
> usb: device: class: gs_usb: unify application event callbacks

- subsys/usb/device/class/Kconfig.gs_usb
Default to a max bulk endpoint packet size of 512 bytes if the USB device controller supports high-speed.
> usb: device: class: gs_usb: use bulk EP max packet size to 512 for HS

- app/sample.yaml
- tests/subsys/usb/gs_usb/cxx/testcase.yaml
- tests/subsys/usb/gs_usb/host/testcase.yaml
Remove the use of space-separated lists, which was deprecated in Zephyr
v3.4.
Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>
> app + tests: remove use of space-separated lists

- README.md
Do not restrict the build status badge to builds triggered by pushes.
> README: do not restrict build status badge to pushes

- README.md
Fix the case for the status badge URLs. The GitHub mobile app treats these as case-sensitive.
> README: fix case for status badge URLs

- app/src/main.c
Include the "git describe" output in the CANnectivity boot banner when available.
> app: src: main: include git describe output in banner when available

- subsys/usb/device_next/class/gs_usb.c
- Use `NET_BUF_POOL_FIXED_DEFINE()` instead of `NET_BUF_POOL_FIXED_DEFINE()` to ensure UDC driver-compatible buffer alignment and granularity (https://github.com/zephyrproject-rtos/zephyr/pull/74021).
- usb: device: next: class: gs_usb: remove redundant interface assignment (https://github.com/zephyrproject-rtos/zephyr/pull/82600).
- usb: device: next: class: gs_usb: remove redundant `memset()` (https://github.com/zephyrproject-rtos/zephyr/pull/82961).
> usb: device: next: class: gs_usb: catch up with changes in Zephyr main branch

- app/src/main.c
Log records should not include span over multiple lines.
> app: remove empty line from log output

- app/boards/makerbase/mks_canable_v20/mks_canable_v20.conf
- app/boards/makerbase/mks_canable_v20/mks_canable_v20.overlay
- app/sample.yaml
Add configuration for the mks_canable_v20 board.
> app: boards: add configuration for the mks_canable_v20 board

- app/src/usb.c
Add support for the MSOSv2 descriptor when using the USB device_next stack.
> app: usb: add support for the MSOSv2 descriptor when using usbd_next

- include/cannectivity/usb/class/gs_usb.h
- subsys/usb/device/class/Kconfig.gs_usb
- subsys/usb/device/class/gs_usb.c
- subsys/usb/device_next/class/Kconfig.gs_usb
- subsys/usb/device_next/class/gs_usb.c
Convert the dummy endpoint to a fully functional bulk OUT endpoint in order to be compatible with gs_usb drivers selecting the first available IN/OUT endpoints for use, and introduce a Kconfig option for turning off gs_usb driver compatibility mode.
The Linux kernel gs_usb driver prior to kernel v6.12.5 uses hardcoded USB endpoint addresses 0x81 (bulk IN) and 0x02 (bulk OUT). The same assumption on USB endpoint addresses may be present in other drivers as well (e.g. python-can).
Depending on the capabilities of the USB device controller, the requested USB endpoint addresses may be rewritten by the Zephyr USB device stack at runtime. Enabling compatibility mode will include a second bulk OUT endpoint to ensure correct operation with gs_usb drivers using the hardcoded USB endpoint addresses …
> usb: device: gs_usb: convert dummy endpoint to fully functional OUT ep

- app/src/main.c
Include the "git describe" output in the CANnectivity boot banner when available.
> [Backport v1.0] app: src: main: include git describe output in banner when available

- app/src/main.c
Remove tailing newline character from the log message. Logging should not span over multiple lines as it makes it harder to process automatically.
Signed-off-by: David Schneider <schneidav81@gmail.com>
(cherry picked from commit 42bbcd1cff9a89c96c88af6d26ce3b6707f2c454)
> [Backport v1.0] app: remove empty line from log output

- subsys/usb/device_next/class/gs_usb.c
Move a few constant pointers from "struct gs_usb_data" to a new "struct gs_usb_config" struct, which can reside in flash.
Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>
(cherry picked from commit b1ae7032442ccfc062cb7ce3f808083ed5612abc)
> [Backport v1.0] usb: device: next: class: gs_usb: move a few pointers to a const struct

- include/cannectivity/usb/class/gs_usb.h
- subsys/usb/device/class/Kconfig.gs_usb
- subsys/usb/device/class/gs_usb.c
- subsys/usb/device_next/class/Kconfig.gs_usb
- subsys/usb/device_next/class/gs_usb.c
Convert the dummy endpoint to a fully functional bulk OUT endpoint in order to be compatible with gs_usb drivers selecting the first available IN/OUT endpoints for use, and introduce a Kconfig option for turning off gs_usb driver compatibility mode.
The Linux kernel gs_usb driver prior to kernel v6.12.5 uses hardcoded USB endpoint addresses 0x81 (bulk IN) and 0x02 (bulk OUT). The same assumption on USB endpoint addresses may be present in other drivers as well (e.g. python-can).
Depending on the capabilities of the USB device controller, the requested USB endpoint addresses may be rewritten by the Zephyr USB device stack at runtime. Enabling compatibility mode will include a second bulk OUT endpoint to ensure correct operation with gs_usb drivers using the hardcoded USB endpoint addresses …
> [Backport v1.0] usb: device: gs_usb: convert dummy endpoint to fully functional OUT ep

- .github/workflows/build.yml
- .github/workflows/docs.yml
Bump the GitHub runners from Ubuntu 22.04 to Ubuntu 24.04.
> github: bump runners from Ubuntu 22.04 to Ubuntu 24.04

- app/boards/candlelightfd_stm32g0b1xx.overlay
- app/boards/candlelightfd_stm32g0b1xx_dual.conf
- app/boards/candlelightfd_stm32g0b1xx_dual.overlay
- app/src/led.c
Add support for the candlelightFD board from Linux Automation.
The board optionally supports a second CAN channel, but only provides two LEDs (RX/TX) in total. To work around this limitation, the "dual" configuration uses the RX LED for channel 0 state/activity, and the TX LED  for channel 1 state/activity.
Since this board has no activity LEDs in its dual configuration, add a small change to the LED initialisation code to support this.
> app: boards: add support for the candlelightFD board

- app/src/led.c
Fix CAN channel state indication when no CAN channel activity LEDs are present.
Fixes: a2794f9fefac5307fa59ffe91b64f386c2a1778b
> app: src: led: fix state indication without activity LEDs

- app/src/led.c
Fix CAN channel state indication when no CAN channel activity LEDs are present.
Fixes: a2794f9fefac5307fa59ffe91b64f386c2a1778b
Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>
(cherry picked from commit 2ee71e1c570ac7c89c16cd2a84793600cc77a4fc)
> [Backport v1.0] app: src: led: fix state indication without activity LEDs

- README.md
- app/CMakeLists.txt
- app/Kconfig
- app/boards/canbardo_same70n20b.overlay
- app/boards/candlelight_stm32f072xb.overlay
- app/boards/candlelightfd_stm32g0b1xx.overlay
- app/boards/candlelightfd_stm32g0b1xx_dual.overlay
- app/boards/lpcxpresso55s16_lpc55s16.overlay
- app/boards/mks_canable_v20_stm32g431xx.overlay
- app/boards/native_sim.overlay
- app/boards/nucleo_h723zg_stm32h723xx.overlay
- app/boards/ucan_stm32f072xb.overlay
- app/boards/usb2canfdv1_stm32g0b1xx.overlay
- app/dts/bindings/cannectivity.yaml
- app/src/dfu.c
- app/src/led.c
- app/src/main.c
- doc/index.rst
Switch from representing LEDs as GPIOs to representing LEDs as LEDs:
- Rename the state-gpios/activity-gpios devicetree properties to state-led/activity-leds and use phandles to refer to existing LED devicetree nodes. This simplifies the CANnectivity firmware devicetree overlays and avoids having to repeat LED GPIO specifications already present in the board devicetree.
- Switch from using the Zephyr GPIO API for controlling LEDs to using the Zephyr LED API. This allows using LEDs controlled by a dedicated LED controller IP/external IC.
Suggested-by: @fabiobaltieri
> app: led: represent LEDs as LEDs, not GPIOs

- app/Kconfig
The Kconfig option CONFIG_CANNECTIVITY_DFU_BUTTON must select CONFIG_GPIO as the button is read using the Zephyr GPIO API.
Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>
(cherry picked from commit b11373facf30c7a7fa021b5cc507766bc2a64ed4)
> [Backport v1.0] app: dfu: CONFIG_CANNECTIVITY_DFU_BUTTON must select CONFIG_GPIO

- .github/workflows/docs.yml
Only deploy documentation on pushes to the main branch.
> github: workflows: docs: only deploy documentation from main branch

- doc/building.rst
- doc/conf.py
- doc/index.rst
- doc/module.rst
- doc/porting.rst
Use the intersphinx extension for linking to Zephyr documentation instead of manually linking.
> doc: use intersphinx for linking to Zephyr documentation

- app/boards/canbardo_same70n20b.overlay
- app/boards/candlelight_stm32f072xb.overlay
- app/boards/candlelightfd_stm32g0b1xx.overlay
- app/boards/candlelightfd_stm32g0b1xx_dual.overlay
- app/boards/lpcxpresso55s16_lpc55s16.overlay
- app/boards/mks_canable_v20_stm32g431xx.overlay
- app/boards/native_sim.overlay
- app/boards/nucleo_h723zg_stm32h723xx.overlay
- app/boards/ucan_stm32f072xb.overlay
- app/boards/usb2canfdv1_stm32g0b1xx.overlay
Include the generic app.overlay in board-specific overlays instead of repeating the common configuration.
> app: boards: include app.overlay in board overlays

- app/app.overlay
- dts/bindings/usb/gs_usb.yaml
- subsys/usb/device/class/gs_usb.c
- subsys/usb/device_next/class/gs_usb.c
Add support for setting the gs_usb class interface descriptor string (iInterface). The string can be set per instance via the devicetree label property.
The interface descriptor string can be used by host software for identifying the gs_usb class interface on composite USB devices.
Inspired-by: @fabiobaltieri in https://github.com/zephyrproject-rtos/zephyr/pull/84062
> usb: class: gs_usb: add support for setting the interface descriptor str

- app/src/usb.c
- subsys/usb/device/class/gs_usb.c
- subsys/usb/device_next/class/gs_usb.c
Remove the unnecessary USB Interface Association Descriptor (IAD). The gs_usb device class has only one USB interface.
> usb: device: class: gs_usb: remove interface association descriptor

- tests/subsys/usb/gs_usb/host/prj_usbd_next.conf
Remove outdated comment from the gs_usb host test configuration.
> tests: usb: gs_usb: host: remove outdated comment

- tests/subsys/usb/gs_usb/host/src/usb.c
Change the USB triplet of the gs_usb host test to (0, 0, 0) to reflect that the gs_usb class no longer uses an Interface Association Descriptor (IAD).
Fixes: 10a8cd4ae60f6bf15db11eed30a042a0d544912e
> tests: usb: gs_usb: host: reflect that the class no longer uses IADs

- app/src/usb.c
- tests/subsys/usb/gs_usb/host/src/usb.c
Switch from usbd_register_all_classes() to usbd_register_class() as the former is mostly meant as a utility function for use in in-tree Zephyr samples/tests.
Using usbd_register_class() furthermore improves error handling as it will fail if the expected class instance is not available.
> usbd_next: switch from usbd_register_all_classes() to usbd_register_class()

- app/Kconfig
- app/boards/canbardo_same70n20b.conf
- app/boards/candlelight_stm32f072xb.conf
- app/boards/candlelightfd_stm32g0b1xx_dual.conf
- app/boards/mks_canable_v20_stm32g431xx.conf
- app/boards/ucan_stm32f072xb.conf
- app/src/usb.c
- Add a Kconfig option for indicating that a CANnectivity USB device is self-powered (the default as this applies to most development boards where power is supplied via an onboard debugger).
- Disable CONFIG_CANNECTIVITY_USB_SELF_POWERED for bus-powered boards.
> app: add support for indicating bus-powered vs. self-powered devices

- app/app.overlay
- dts/bindings/usb/gs_usb.yaml
- subsys/usb/device/class/gs_usb.c
- subsys/usb/device_next/class/gs_usb.c
- tests/subsys/usb/gs_usb/cxx/app.overlay
- tests/subsys/usb/gs_usb/host/app.overlay
Get rid of the "on-bus: usb" devicetree requirement to match upstream Zephyr USB class devicetree bindings.
> usb: device: class: gs_usb: get rid of "on-bus" devicetree requirement

- 99-cannectivity.rules
The custom udev rules are strictly only needed for Linux kernels prior to v6.15-rc1 and when running the CANnectivity test suites (as they require user access to the USB devices).
Official Linux kernel driver support was added in the following commit: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=32f08b22f3b88b7ba43fa8f4090dfd9575343256
> udev: add note describing when these custom udev rules are needed

- west.yml
Switch from the cmsis to the cmsis_6 module, which is now required for Cortex-M.
> manifest: switch to cmsis_6

- .github/workflows/build.yml
Bump the Python version used in CI to v3.12.
> github: workflows: build: bump Python version to v3.12

- subsys/usb/device_next/class/Kconfig.gs_usb
Select the newly introduced Kconfig CONFIG_UDC_ENABLE_SOF when timestamping on start-of-frame events is enabled.
> usb: device: next: class: gs_usb: select UDC_ENABLE_SOF when needed

- README.md
Fix the path to the cannectivity/app folder used in the sysbuild example.
> README: fix path used in sysbuild example

- west.yml
The current version of CANnectivity was tested against Zephyr v4.2.0. Change the manifest to reflect this.
> manifest: change manifest to track Zephyr v4.2-branch

- .gitignore
- app/boards/native_sim_native_64_usbd_next.overlay
- app/boards/native_sim_usbd_next.overlay
- scripts/cannectivity.conf
- scripts/cannectivity.conf.stop
- scripts/run-host-tests.sh
- west.yml
- Add devicetree overlays for running CANnectivity on native_sim using USB/IP and SocketCAN.
-  Add script for running the Zephyr CAN host test suite using CANnectivity running in native_sim for providing the USB to CAN adapter.
> app: add native_sim configuration for usbd_next

- .github/workflows/build.yml
- .github/workflows/docs.yml
Restrict the GitHub workflows to read permissions and do not persist the credentials where not needed.
> github: restrict permissions to read and do not persist credentials

- app/sample.yaml
- tests/subsys/usb/gs_usb/cxx/testcase.yaml
- tests/subsys/usb/gs_usb/host/testcase.yaml
Do not exclude the 32-bit native_sim platform when building.
> app + tests: do not exclude 32-bit native_sim

- scripts/run-host-tests.sh
Run CANnectivity under valgrind/memcheck when running the host tests.
> scripts: run-host-tests: run CANnectivity under valgrind memcheck

- .github/workflows/build.yml
Move macOS build testing from macos-13 + macos-14 to macos-15.
> ci: workflows: build: move build testing to macOS 15

- .github/workflows/build.yml
Setup the ccache caching key for action-zephyr-setup and print ccache stats after each run.
> ci: workflows: build: setup ccache caching and print statistics
